### PR TITLE
Optimize the code && delete SNAPSHOT version

### PR DESCRIPTION
**Pull request by pirateskipper**
Should be the same as other open source projects, SNAPSHOT logo version should not be used

### CODE REVIEW

**Comment by pirateskipper** [comment]
@shulieTech Should be the same as other open source projects, SNAPSHOT logo version should not be used.So changed the pom version setting to replace SNAPSHOT.Thanks

**Comment by pirateskipper** [comment]
@shulieTech and it is recommended to use the <revision/> tag to manage the unified settings version.

**Comment by shulieTech** [comment]
Thank you very much for your PR, we will release a big new version in 2 weeks.
Welcome to continue pulling request.

**Comment by pirateskipper** [comment]
look forward to becoming a committer of this project. Please help us to lead how to become a committer of this project. @shulieTech

**Pull request merged**
